config/routes.rb
Rails.application.routes.draw do

  root to: "cats#index"

  resources :cats

  resources :cat_rental_requests do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :users

  resource :session

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_reader :password

  validates :user_name, presence: true
  validates :user_name, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :cats,
          class_name: "Cat",
          foreign_key: :user_id,
          primary_key: :id

  has_many :sessions

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(pt)
    @password = pt
    self.password_digest = BCrypt::Password.create(pt)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token(user_agent)
    session = Session.create(
      user_id: self.id,
      token: SecureRandom::urlsafe_base64(16),
      user_agent: user_agent
    )
    session.token
  end

  def cleanup_sessions
    old_sessions = Session.where(user_id: self.id).where("sessions.created_at < ?", 7.days.ago)
    old_sessions.each(&:delete)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to cats_url
    else
      flash[:errors] ||= []
      flash[:errors] << "Unable to create that account"
      render :new
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<form action="<%= user.persisted? ? user_url(user) : users_url %>" method="post">
  <%= get_form_auth_token %>
  <% if user.persisted? %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <table>
    <tr>
      <td><label for="user_name"><strong>Name</strong></label></td>
      <td><input type="text" name="user[user_name]" id="user_name" value="<%= user.user_name %>"></td>
    </tr>
    <tr>
      <td><label for="password"><strong>Password</strong></label></td>
      <td><input type="password" name="user[password]" id="password"></td>
    </tr>
  </table>
  <input type="submit" value="Sign up!">

</form>

app/views/users/new.html.erb
<h1 id="new_user">Sign up</h1>
<div id="user_form">
  <%= render partial: 'form', locals: { user: @user } %>
</div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.user_name %></h1>