config/routes.rb
Rails.application.routes.draw do

  root to: "cats#index"

  resources :cats

  resources :cat_rental_requests do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :users

  resource :session

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  before_validation :set_status

  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }

  belongs_to :cat

  def approve!
    raise "An overlapping APPROVED request exists." unless overlapping_approved_requests.empty?
    self.class.transaction do
      update(status: "APPROVED")
      overlapping_pending_requests.each do |request|
        request.update(status: "DENIED")
      end
    end
  end

  def deny!
    update(status: "DENIED")
  end

  def overlapping_requests
    sql_params = {
      cat_id: cat_id,
      start_date: start_date,
      end_date: end_date,
      id: id
    }
    CatRentalRequest.select("*").where(<<-SQL, sql_params)
      id != :id
    AND
      cat_id = :cat_id
    AND
      (start_date BETWEEN :start_date AND :end_date
      OR
      end_date BETWEEN :start_date AND :end_date)
    SQL
  end

  def overlapping_pending_requests
    sql_params = {
      cat_id: cat_id,
      start_date: start_date,
      end_date: end_date,
      id: id,
      status: "PENDING"
    }
    CatRentalRequest.select("*").where(<<-SQL, sql_params)
      id != :id
    AND
      cat_id = :cat_id
    AND
      status = :status
    AND
      (start_date BETWEEN :start_date AND :end_date
      OR
      end_date BETWEEN :start_date AND :end_date)
    SQL
  end

  def overlapping_approved_requests
    sql_params = {
      cat_id: cat_id,
      start_date: start_date,
      end_date: end_date,
      id: id,
      status: "APPROVED"
    }
    CatRentalRequest.select("*").where(<<-SQL, sql_params)
      id != :id
    AND
      cat_id = :cat_id
    AND
      status = :status
    AND
      (start_date BETWEEN :start_date AND :end_date
      OR
      end_date BETWEEN :start_date AND :end_date)
    SQL
  end

  private

    def set_status
      self.status ||= "PENDING"
    end

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :current_user_owns_cat, only: [:approve, :deny]

  def index
    @requests = CatRentalRequest.all
  end

  def show
    @request = CatRentalRequest.find(params[:id])
  end

  def new
    @request = CatRentalRequest.new()
    @cats = Cat.all
  end

  def edit
    @request = CatRentalRequest.find(params[:id])
    @cats = Cat.all
  end

  def update
    @request = CatRentalRequest.find(params[:id])
    if @request.valid?
      @request.update(request_params)
      redirect_to cat_url(@request.cat)
    else
      @request.errors.full_messages
    end
  end

  def create
    @request = CatRentalRequest.new(request_params)
    if @request.valid?
      @request.save!
      redirect_to cat_url(@request.cat)
    else
      @request.errors.full_messages
    end
  end

  def approve
    @request.approve!
    redirect_to cat_url(@request.cat)
  end

  def deny
    @request.deny!
    redirect_to cat_url(@request.cat)
  end

  private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end

  def current_user_owns_cat
    @request = CatRentalRequest.find(params[:id])
    if @request.cat.user_id != current_user.id
      flash[:errors] ||= []
      flash[:errors] << "You do not own that cat, thief!"
      redirect_to cat_url(@request.cat)
    end
  end

end

app/helpers/catrentalrequests_helper.rb
module CatrentalrequestsHelper
end

app/views/cat_rental_requests/_form.html.erb
<form action="<%= request.persisted? ? cat_rental_request_url(request) : cat_rental_requests_url %>" method="post">
  <%= get_form_auth_token %>
  <% if request.persisted? %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <table>
    <tr>
      <td><label for="request_cat_id"><strong>Cat ID</strong></label></td>

      <td>
        <select name="cat_rental_request[cat_id]" id="request_cat_id">
          <option></option>
          <% cats.each do |cat_to_request| %>
            <option value="<%= cat_to_request.id %>" <% if request.persisted? && request.cat.id == cat_to_request.id %> selected <% end %>>
              <%= cat_to_request.id %>
            </option>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td><label for="request_start_date"><strong>Start Date</strong></label></td>
      <td>
        <input type="date" name="cat_rental_request[start_date]" value="<%= request.start_date %>" id="request_start_date">
      </td>
    </tr>
    <tr>
      <td><label for="request_end_date"><strong>End Date</strong></label></td>
      <td>
        <input type="date" name="cat_rental_request[end_date]" value="<%= request.end_date %>" id="request_end_date">
      </td>
    </tr>
    <% if request.persisted? %>
    <tr>
      <td><label for="request_status"><strong>Status</strong></label></td>
      <td>
        <select name="cat_rental_request[status]" id="request_status">
          <option value="PENDING" <% if request.status == "PENDING" %> selected <% end %>>PENDING</option>
          <option value="APPROVED" <% if request.status == "APPROVED" %> selected <% end %>>APPROVED</option>
          <option value="DENIED" <% if request.status == "DENIED" %> selected <% end %>>DENIED</option>
        </select>
      </td>
    </tr>
    <% end %>
  </table>
  <input type="submit" value="Create Cat Rental Request">

</form>

app/views/cat_rental_requests/edit.html.erb
<h1 id="edit_request">Edit Your Cat Rental Request</h1>
<div id="request_form">
  <%= render partial: 'form', locals: { request: @request, cats: @cats } %>
</div>

app/views/cat_rental_requests/new.html.erb
<h1>Rent a Cat</h1>

<form action=<%=cat_rental_requests_url%> method="POST">


  <select name="cat_rental_request[cat_id]" id="cat_id">
    <% @cats.each do |cat| %>
      <option value="<%=cat.id%>"><%=cat.name.capitalize%></option>
    <%end%>
  </select>
  <br>
  <label for="rental_start_date">Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" id="rental_start_date">
  <br>
  <label for="rental_end_date">End Date</label>
  <input type="date" name="cat_rental_request[end_date]" id="rental_end_date">
  <br>

  <input type="submit" value="Rent cat ">
</form>