config/routes.rb
Rails.application.routes.draw do

  root to: "cats#index"

  resources :cats

  resources :cat_rental_requests do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :users

  resource :session

end

app/models/cat.rb
class Cat < ActiveRecord::Base

  validates :age, :name, :sex, presence: true
  validates :age, numericality: true
  validates :sex, inclusion: { in: %w(M F) }

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    :dependent => :destroy
  )
  belongs_to :owner,
            class_name: "User",
            foreign_key: :user_id,
            primary_key: :id

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :current_user_owns_cat, only: [:edit, :update]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new(cat_params)
  end

  def edit
  end

  def update
    if @cat.valid?
      @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      @cat.errors.full_messages
    end
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.valid?
      @cat.save!
      redirect_to cat_url(@cat)
    else
      @cat.errors.full_messages
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :color, :age, :birth_date, :sex)
  end

  def current_user_owns_cat
    @cat = Cat.find(params[:id])
    if @cat.user_id != current_user.id
      flash[:errors] ||= []
      flash[:errors] << "You do not own that cat, thief!"
      redirect_to cat_url(@cat)
    end
  end

end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_cat.html.erb
<h3><%= link_to cat.name, cat_url(cat) %></h3>
<table>
  <tr>
    <td><%= cat.color %></td>
    <td><%= cat.sex %></td>
  </tr>
</table>

app/views/cats/_cat_rental.html.erb
<h3><%= link_to "Request ID: #{request.id}", edit_cat_rental_request_url(request) %></h3>
<p><%= request.start_date %> to <%= request.end_date %></p>
<p><%= request.status %></p>
<% if request.status == "PENDING" && current_user && current_user.id == request.cat.owner.id %>
  <%= button_to [:approve, request] do %>Approve<% end %>
  <%= button_to [:deny, request] do %>Deny<% end %>
<% end %>

app/views/cats/_form.html.erb
<form action="<%= cat.persisted? ? cat_url(cat) : cats_url %>" method="post">
  <%= get_form_auth_token %>
  <% if cat.persisted? %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <table>
    <tr>
      <td><label for="cat_name"><strong>Name</strong></label></td>
      <td><input type="text" name="cat[name]" id="cat_name" value="<%= cat.name %>"></td>
    </tr>
    <tr>
      <td><label for="cat_age"><strong>Age</strong></label></td>
      <td><input type="text" name="cat[age]" id="cat_age" value="<%= cat.age %>"></td>
    </tr>
    <tr>
      <td><strong>Sex</strong></td>
      <td></td>
    </tr>
    <tr>
      <td><input type="radio" name="cat[sex]" id="cat_sex_female" value="F"
        <% if cat.sex == "F" %> checked=1 <% end %>></td>
      <td><label for="cat_sex_female">Female</label></td>
    </tr>
    <tr>
      <td><input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
        <% if cat.sex == "M" %> checked=1 <% end %>>
</td>
      <td><label for="cat_sex_male">Male</label></td>
    </tr>
    <tr>
      <td><label for="cat_color"><strong>Color</strong></label></td>

      <td>
        <select name="cat[color]" id="cat_color">
          <option></option>
          <option value="brown" <% if cat.color == "brown" %> selected <% end %>>Brown</option>
          <option value="black" <% if cat.color == "black" %> selected <% end %>>Black</option>
          <option value="blue" <% if cat.color == "blue" %> selected <% end %>>Blue</option>
          <option value="white" <% if cat.color == "white" %> selected <% end %>>White</option>
          <option value="orange" <% if cat.color == "orange" %> selected <% end %>>Orange</option>
          <option value="tabby" <% if cat.color == "tabby" %> selected <% end %>>Tabby</option>
        </select>
      </td>
    </tr>
    <tr>
      <td><label for="cat_birth_date"><strong>Birth Date</strong></label></td>

      <td>
        <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>" id="cat_birth_date">
      </td>

    </tr>
  </table>
  <input type="submit" value="Create Cat">

</form>

app/views/cats/edit.html.erb
<h1 id="edit_cat">Edit <%= @cat.name %>'s Information</h1>
<div id="cat_form">
  <%= render partial: 'form', locals: { cat: @cat } %>
</div>

app/views/cats/index.html.erb
<h1 id="cats">Cats</h1>
<% @cats.each do |cat| %>

<div><%= render partial: 'cat', locals: {cat: cat} %></div>

<% end %>

app/views/cats/new.html.erb
<h1 id="new_cat">New Cat</h1>
<div id="cat_form">
  <%= render partial: 'form', locals: { cat: @cat } %>
</div>

app/views/cats/show.html.erb
<h3><%= @cat.name %></h3>
<table>
  <tr>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
  </tr>
</table>
<p>Rental Requests: <%= @cat.rental_requests.count %></p>
<div>
  <% @cat.rental_requests.order(:start_date).each do |request| %>
    <%= render partial: "cat_rental", locals: {request: request} %>
  <% end %>
</div>